
server:
  port: 10001
spring:
  application:
    name: zhouprovider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_mall?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9091/eureka
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.mall.demo.pojo


